name: "Check API"

on:
  push:
    branches: [ "main" ]
    paths: [ "Makefile", "api.bs", "images/**", ".github/workflows/check.yml" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "Makefile", "api.bs", "images/**", ".github/workflows/check.yml" ]

jobs:
  build:
    name: "Build HTML"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - run: make
